import { RestWeatherApiRawData } from "./RestWeatherApi";

const response: RestWeatherApiRawData = {
  "location": {
    "name": "Lille MOCKED",
    "region": "Nord-Pas-de-Calais",
    "country": "France",
    "lat": 50.633,
    "lon": 3.067,
    "tz_id": "Europe/Paris",
    "localtime_epoch": 1773585636,
    "localtime": "2026-03-15 15:40"
  },
  "current": {
    "last_updated_epoch": 1773585000,
    "last_updated": "2026-03-15 15:30",
    "temp_c": 12.2,
    "temp_f": 54,
    "is_day": 1,
    "condition": {
      "text": "Ensoleillé",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
      "code": 1000
    },
    "wind_mph": 13,
    "wind_kph": 20.9,
    "wind_degree": 225,
    "wind_dir": "SW",
    "pressure_mb": 1014,
    "pressure_in": 29.94,
    "precip_mm": 0,
    "precip_in": 0,
    "humidity": 44,
    "cloud": 25,
    "feelslike_c": 10.1,
    "feelslike_f": 50.1,
    "windchill_c": 9.6,
    "windchill_f": 49.4,
    "heatindex_c": 11.9,
    "heatindex_f": 53.3,
    "dewpoint_c": -0.9,
    "dewpoint_f": 30.4,
    "vis_km": 10,
    "vis_miles": 6,
    "uv": 1.7,
    "gust_mph": 15.4,
    "gust_kph": 24.8,
    "short_rad": 592.46,
    "diff_rad": 83.66,
    "dni": 872.76,
    "gti": 0
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2026-03-15",
        "date_epoch": 1773532800,
        "day": {
          "maxtemp_c": 11.9,
          "maxtemp_f": 53.4,
          "mintemp_c": 2.8,
          "mintemp_f": 37,
          "avgtemp_c": 7.3,
          "avgtemp_f": 45.2,
          "maxwind_mph": 20.1,
          "maxwind_kph": 32.4,
          "totalprecip_mm": 0.17,
          "totalprecip_in": 0.01,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 63,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 72,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Pluie éparse à proximité",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "code": 1063
          },
          "uv": 0.6
        },
        "astro": {
          "sunrise": "07:02 AM",
          "sunset": "06:52 PM",
          "moonrise": "05:52 AM",
          "moonset": "02:30 PM",
          "moon_phase": "Waning Crescent",
          "moon_illumination": 18,
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1773529200,
            "time": "2026-03-15 00:00",
            "temp_c": 4,
            "temp_f": 39.1,
            "is_day": 0,
            "condition": {
              "text": "Clair",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 301,
            "wind_dir": "WNW",
            "pressure_mb": 1011,
            "pressure_in": 29.84,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 76,
            "cloud": 2,
            "feelslike_c": 2,
            "feelslike_f": 35.7,
            "windchill_c": 2,
            "windchill_f": 35.7,
            "heatindex_c": 4,
            "heatindex_f": 39.1,
            "dewpoint_c": 0.2,
            "dewpoint_f": 32.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.3,
            "gust_kph": 15,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773532800,
            "time": "2026-03-15 01:00",
            "temp_c": 3.8,
            "temp_f": 38.8,
            "is_day": 0,
            "condition": {
              "text": "Partiellement nuageux",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 297,
            "wind_dir": "WNW",
            "pressure_mb": 1011,
            "pressure_in": 29.86,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 77,
            "cloud": 2,
            "feelslike_c": 2,
            "feelslike_f": 35.7,
            "windchill_c": 2,
            "windchill_f": 35.7,
            "heatindex_c": 3.8,
            "heatindex_f": 38.8,
            "dewpoint_c": 0.2,
            "dewpoint_f": 32.3,
            "will_it_rain": 0,
            "chance_of_rain": 25,
            "will_it_snow": 0,
            "chance_of_snow": 10,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.5,
            "gust_kph": 13.7,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773536400,
            "time": "2026-03-15 02:00",
            "temp_c": 3.6,
            "temp_f": 38.5,
            "is_day": 0,
            "condition": {
              "text": "Clair",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 292,
            "wind_dir": "WNW",
            "pressure_mb": 1012,
            "pressure_in": 29.87,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 78,
            "cloud": 0,
            "feelslike_c": 2,
            "feelslike_f": 35.5,
            "windchill_c": 2,
            "windchill_f": 35.5,
            "heatindex_c": 3.6,
            "heatindex_f": 38.5,
            "dewpoint_c": 0.1,
            "dewpoint_f": 32.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.2,
            "gust_kph": 13.1,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773540000,
            "time": "2026-03-15 03:00",
            "temp_c": 3.4,
            "temp_f": 38.2,
            "is_day": 0,
            "condition": {
              "text": "Clair",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 284,
            "wind_dir": "WNW",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 78,
            "cloud": 0,
            "feelslike_c": 1.6,
            "feelslike_f": 35,
            "windchill_c": 1.6,
            "windchill_f": 35,
            "heatindex_c": 3.4,
            "heatindex_f": 38.2,
            "dewpoint_c": 0,
            "dewpoint_f": 32,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.7,
            "gust_kph": 14,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773543600,
            "time": "2026-03-15 04:00",
            "temp_c": 3.2,
            "temp_f": 37.8,
            "is_day": 0,
            "condition": {
              "text": "Clair",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 281,
            "wind_dir": "W",
            "pressure_mb": 1012,
            "pressure_in": 29.9,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 78,
            "cloud": 0,
            "feelslike_c": 1.4,
            "feelslike_f": 34.6,
            "windchill_c": 1.4,
            "windchill_f": 34.6,
            "heatindex_c": 3.3,
            "heatindex_f": 37.9,
            "dewpoint_c": -0.1,
            "dewpoint_f": 31.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.8,
            "gust_kph": 14.1,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773547200,
            "time": "2026-03-15 05:00",
            "temp_c": 3.1,
            "temp_f": 37.5,
            "is_day": 0,
            "condition": {
              "text": "Clair",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 274,
            "wind_dir": "W",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 79,
            "cloud": 7,
            "feelslike_c": 1.3,
            "feelslike_f": 34.4,
            "windchill_c": 1.3,
            "windchill_f": 34.4,
            "heatindex_c": 3.1,
            "heatindex_f": 37.5,
            "dewpoint_c": -0.2,
            "dewpoint_f": 31.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.4,
            "gust_kph": 13.5,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773550800,
            "time": "2026-03-15 06:00",
            "temp_c": 2.9,
            "temp_f": 37.3,
            "is_day": 0,
            "condition": {
              "text": "Clair",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 270,
            "wind_dir": "W",
            "pressure_mb": 1013,
            "pressure_in": 29.92,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 80,
            "cloud": 5,
            "feelslike_c": 1.2,
            "feelslike_f": 34.1,
            "windchill_c": 1.2,
            "windchill_f": 34.1,
            "heatindex_c": 2.9,
            "heatindex_f": 37.3,
            "dewpoint_c": -0.1,
            "dewpoint_f": 31.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.4,
            "gust_kph": 13.5,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773554400,
            "time": "2026-03-15 07:00",
            "temp_c": 2.8,
            "temp_f": 37,
            "is_day": 0,
            "condition": {
              "text": "Clair",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 264,
            "wind_dir": "W",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 81,
            "cloud": 3,
            "feelslike_c": 1.1,
            "feelslike_f": 34,
            "windchill_c": 1.1,
            "windchill_f": 34,
            "heatindex_c": 2.8,
            "heatindex_f": 37,
            "dewpoint_c": -0.1,
            "dewpoint_f": 31.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8,
            "gust_kph": 12.9,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773558000,
            "time": "2026-03-15 08:00",
            "temp_c": 3.6,
            "temp_f": 38.5,
            "is_day": 1,
            "condition": {
              "text": "Ensoleillé",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 248,
            "wind_dir": "WSW",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 79,
            "cloud": 9,
            "feelslike_c": 2.2,
            "feelslike_f": 36,
            "windchill_c": 2.2,
            "windchill_f": 36,
            "heatindex_c": 3.6,
            "heatindex_f": 38.5,
            "dewpoint_c": 0.4,
            "dewpoint_f": 32.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 0.2,
            "short_rad": 34.92,
            "diff_rad": 14.02,
            "dni": 0,
            "gti": 12.73
          },
          {
            "time_epoch": 1773561600,
            "time": "2026-03-15 09:00",
            "temp_c": 5.6,
            "temp_f": 42.1,
            "is_day": 1,
            "condition": {
              "text": "Ensoleillé",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 236,
            "wind_dir": "WSW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 72,
            "cloud": 13,
            "feelslike_c": 4.4,
            "feelslike_f": 39.9,
            "windchill_c": 4.4,
            "windchill_f": 39.9,
            "heatindex_c": 5.6,
            "heatindex_f": 42.1,
            "dewpoint_c": 0.9,
            "dewpoint_f": 33.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.5,
            "gust_kph": 8.8,
            "uv": 0.6,
            "short_rad": 107.36,
            "diff_rad": 31.39,
            "dni": 524.59,
            "gti": 0
          },
          {
            "time_epoch": 1773565200,
            "time": "2026-03-15 10:00",
            "temp_c": 7.2,
            "temp_f": 45,
            "is_day": 1,
            "condition": {
              "text": "Ensoleillé",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 199,
            "wind_dir": "SSW",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 65,
            "cloud": 20,
            "feelslike_c": 5.2,
            "feelslike_f": 41.3,
            "windchill_c": 5.2,
            "windchill_f": 41.3,
            "heatindex_c": 7.2,
            "heatindex_f": 45,
            "dewpoint_c": 1.2,
            "dewpoint_f": 34.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.5,
            "gust_kph": 13.6,
            "uv": 1.2,
            "short_rad": 186.04,
            "diff_rad": 43.18,
            "dni": 480.99,
            "gti": 0
          },
          {
            "time_epoch": 1773568800,
            "time": "2026-03-15 11:00",
            "temp_c": 8.8,
            "temp_f": 47.8,
            "is_day": 1,
            "condition": {
              "text": "Ensoleillé",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 205,
            "wind_dir": "SSW",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 56,
            "cloud": 6,
            "feelslike_c": 6.6,
            "feelslike_f": 43.9,
            "windchill_c": 6.6,
            "windchill_f": 43.9,
            "heatindex_c": 8.8,
            "heatindex_f": 47.8,
            "dewpoint_c": 0.5,
            "dewpoint_f": 33,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.9,
            "gust_kph": 15.9,
            "uv": 1.9,
            "short_rad": 258.6,
            "diff_rad": 51.98,
            "dni": 483.85,
            "gti": 0
          },
          {
            "time_epoch": 1773572400,
            "time": "2026-03-15 12:00",
            "temp_c": 10,
            "temp_f": 49.9,
            "is_day": 1,
            "condition": {
              "text": "Ensoleillé",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 210,
            "wind_dir": "SSW",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 48,
            "cloud": 0,
            "feelslike_c": 7.7,
            "feelslike_f": 45.8,
            "windchill_c": 7.7,
            "windchill_f": 45.8,
            "heatindex_c": 10,
            "heatindex_f": 49.9,
            "dewpoint_c": -0.6,
            "dewpoint_f": 31,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.9,
            "gust_kph": 19.1,
            "uv": 2.5,
            "short_rad": 321.66,
            "diff_rad": 58.3,
            "dni": 500.61,
            "gti": 0
          },
          {
            "time_epoch": 1773576000,
            "time": "2026-03-15 13:00",
            "temp_c": 10.9,
            "temp_f": 51.5,
            "is_day": 1,
            "condition": {
              "text": "Ensoleillé",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 11.4,
            "wind_kph": 18.4,
            "wind_degree": 215,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 43,
            "cloud": 0,
            "feelslike_c": 8.6,
            "feelslike_f": 47.5,
            "windchill_c": 8.6,
            "windchill_f": 47.5,
            "heatindex_c": 10.9,
            "heatindex_f": 51.5,
            "dewpoint_c": -1.1,
            "dewpoint_f": 30.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.1,
            "gust_kph": 21.1,
            "uv": 2.7,
            "short_rad": 372.04,
            "diff_rad": 62.81,
            "dni": 526.45,
            "gti": 0
          },
          {
            "time_epoch": 1773579600,
            "time": "2026-03-15 14:00",
            "temp_c": 11.5,
            "temp_f": 52.6,
            "is_day": 1,
            "condition": {
              "text": "Ensoleillé",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.3,
            "wind_kph": 19.8,
            "wind_degree": 222,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 42,
            "cloud": 0,
            "feelslike_c": 9.2,
            "feelslike_f": 48.6,
            "windchill_c": 9.2,
            "windchill_f": 48.6,
            "heatindex_c": 11.5,
            "heatindex_f": 52.6,
            "dewpoint_c": -0.9,
            "dewpoint_f": 30.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.2,
            "gust_kph": 22.8,
            "uv": 2.4,
            "short_rad": 620.8,
            "diff_rad": 84.42,
            "dni": 883.97,
            "gti": 0
          },
          {
            "time_epoch": 1773583200,
            "time": "2026-03-15 15:00",
            "temp_c": 12.2,
            "temp_f": 54,
            "is_day": 1,
            "condition": {
              "text": "Ensoleillé",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 13,
            "wind_kph": 20.9,
            "wind_degree": 225,
            "wind_dir": "SW",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 44,
            "cloud": 25,
            "feelslike_c": 9.7,
            "feelslike_f": 49.4,
            "windchill_c": 9.7,
            "windchill_f": 49.4,
            "heatindex_c": 11.9,
            "heatindex_f": 53.3,
            "dewpoint_c": -0.9,
            "dewpoint_f": 30.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.4,
            "gust_kph": 24.8,
            "uv": 1.7,
            "short_rad": 592.46,
            "diff_rad": 83.66,
            "dni": 872.76,
            "gti": 0
          },
          {
            "time_epoch": 1773586800,
            "time": "2026-03-15 16:00",
            "temp_c": 11.9,
            "temp_f": 53.4,
            "is_day": 1,
            "condition": {
              "text": "Ensoleillé",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 13.9,
            "wind_kph": 22.3,
            "wind_degree": 226,
            "wind_dir": "SW",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 43,
            "cloud": 12,
            "feelslike_c": 9.6,
            "feelslike_f": 49.2,
            "windchill_c": 9.6,
            "windchill_f": 49.2,
            "heatindex_c": 11.9,
            "heatindex_f": 53.4,
            "dewpoint_c": -0.3,
            "dewpoint_f": 31.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.4,
            "gust_kph": 28,
            "uv": 0.8,
            "short_rad": 548.88,
            "diff_rad": 81.4,
            "dni": 903.17,
            "gti": 0
          },
          {
            "time_epoch": 1773590400,
            "time": "2026-03-15 17:00",
            "temp_c": 11.5,
            "temp_f": 52.8,
            "is_day": 1,
            "condition": {
              "text": "Partiellement nuageux",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 13.2,
            "wind_kph": 21.2,
            "wind_degree": 222,
            "wind_dir": "SW",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 48,
            "cloud": 34,
            "feelslike_c": 9.2,
            "feelslike_f": 48.6,
            "windchill_c": 9.2,
            "windchill_f": 48.6,
            "heatindex_c": 11.6,
            "heatindex_f": 52.8,
            "dewpoint_c": 1,
            "dewpoint_f": 33.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.9,
            "gust_kph": 28.9,
            "uv": 0.4,
            "short_rad": 492.02,
            "diff_rad": 77.67,
            "dni": 998.15,
            "gti": 0
          },
          {
            "time_epoch": 1773594000,
            "time": "2026-03-15 18:00",
            "temp_c": 10.5,
            "temp_f": 50.9,
            "is_day": 1,
            "condition": {
              "text": "Partiellement nuageux",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 215,
            "wind_dir": "SW",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 53,
            "cloud": 48,
            "feelslike_c": 8,
            "feelslike_f": 46.4,
            "windchill_c": 8,
            "windchill_f": 46.4,
            "heatindex_c": 10.5,
            "heatindex_f": 50.9,
            "dewpoint_c": 1.4,
            "dewpoint_f": 34.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 19.3,
            "gust_kph": 31.1,
            "uv": 0.1,
            "short_rad": 425.96,
            "diff_rad": 71.53,
            "dni": 1254.49,
            "gti": 0
          },
          {
            "time_epoch": 1773597600,
            "time": "2026-03-15 19:00",
            "temp_c": 10,
            "temp_f": 50,
            "is_day": 0,
            "condition": {
              "text": "Clair",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 13.4,
            "wind_kph": 21.6,
            "wind_degree": 201,
            "wind_dir": "SSW",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 53,
            "cloud": 24,
            "feelslike_c": 7.2,
            "feelslike_f": 45,
            "windchill_c": 7.2,
            "windchill_f": 45,
            "heatindex_c": 10,
            "heatindex_f": 49.9,
            "dewpoint_c": 0.9,
            "dewpoint_f": 33.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 21.2,
            "gust_kph": 34.1,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773601200,
            "time": "2026-03-15 20:00",
            "temp_c": 9.2,
            "temp_f": 48.6,
            "is_day": 0,
            "condition": {
              "text": "Pluie éparse à proximité",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 14.5,
            "wind_kph": 23.4,
            "wind_degree": 209,
            "wind_dir": "SSW",
            "pressure_mb": 1013,
            "pressure_in": 29.92,
            "precip_mm": 0.01,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 55,
            "cloud": 94,
            "feelslike_c": 6.1,
            "feelslike_f": 42.9,
            "windchill_c": 6.1,
            "windchill_f": 42.9,
            "heatindex_c": 9.2,
            "heatindex_f": 48.6,
            "dewpoint_c": 0.7,
            "dewpoint_f": 33.3,
            "will_it_rain": 1,
            "chance_of_rain": 72,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 23.7,
            "gust_kph": 38.1,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773604800,
            "time": "2026-03-15 21:00",
            "temp_c": 9.3,
            "temp_f": 48.7,
            "is_day": 0,
            "condition": {
              "text": "Pluie éparse à proximité",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 17.9,
            "wind_kph": 28.8,
            "wind_degree": 208,
            "wind_dir": "SSW",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0.02,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 58,
            "cloud": 100,
            "feelslike_c": 5.7,
            "feelslike_f": 42.3,
            "windchill_c": 5.7,
            "windchill_f": 42.3,
            "heatindex_c": 9.3,
            "heatindex_f": 48.7,
            "dewpoint_c": 1.5,
            "dewpoint_f": 34.6,
            "will_it_rain": 0,
            "chance_of_rain": 70,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 26.8,
            "gust_kph": 43.2,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773608400,
            "time": "2026-03-15 22:00",
            "temp_c": 8.9,
            "temp_f": 48.1,
            "is_day": 0,
            "condition": {
              "text": "Pluie éparse à proximité",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 20.1,
            "wind_kph": 32.4,
            "wind_degree": 213,
            "wind_dir": "SSW",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0.04,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 63,
            "cloud": 100,
            "feelslike_c": 5,
            "feelslike_f": 41,
            "windchill_c": 5,
            "windchill_f": 41,
            "heatindex_c": 8.9,
            "heatindex_f": 48.1,
            "dewpoint_c": 2.2,
            "dewpoint_f": 36,
            "will_it_rain": 0,
            "chance_of_rain": 69,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 29.7,
            "gust_kph": 47.8,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773612000,
            "time": "2026-03-15 23:00",
            "temp_c": 8.9,
            "temp_f": 48,
            "is_day": 0,
            "condition": {
              "text": "Pluie éparse à proximité",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 19.7,
            "wind_kph": 31.7,
            "wind_degree": 235,
            "wind_dir": "SW",
            "pressure_mb": 1013,
            "pressure_in": 29.9,
            "precip_mm": 0.1,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 73,
            "cloud": 100,
            "feelslike_c": 5,
            "feelslike_f": 41.1,
            "windchill_c": 5,
            "windchill_f": 41.1,
            "heatindex_c": 8.9,
            "heatindex_f": 48,
            "dewpoint_c": 4.3,
            "dewpoint_f": 39.7,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 28.6,
            "gust_kph": 46.1,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          }
        ]
      },
      {
        "date": "2026-03-16",
        "date_epoch": 1773619200,
        "day": {
          "maxtemp_c": 10.6,
          "maxtemp_f": 51.1,
          "mintemp_c": 5.3,
          "mintemp_f": 41.6,
          "avgtemp_c": 8.2,
          "avgtemp_f": 46.8,
          "maxwind_mph": 15.4,
          "maxwind_kph": 24.8,
          "totalprecip_mm": 0.35,
          "totalprecip_in": 0.01,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 71,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 87,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Pluie éparse à proximité",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "code": 1063
          },
          "uv": 0.5
        },
        "astro": {
          "sunrise": "07:00 AM",
          "sunset": "06:54 PM",
          "moonrise": "06:10 AM",
          "moonset": "03:50 PM",
          "moon_phase": "Waning Crescent",
          "moon_illumination": 11,
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1773615600,
            "time": "2026-03-16 00:00",
            "temp_c": 8.9,
            "temp_f": 48.1,
            "is_day": 0,
            "condition": {
              "text": "Pluie éparse à proximité",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 15.4,
            "wind_kph": 24.8,
            "wind_degree": 254,
            "wind_dir": "WSW",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0.02,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 78,
            "cloud": 87,
            "feelslike_c": 5.6,
            "feelslike_f": 42.1,
            "windchill_c": 5.6,
            "windchill_f": 42.1,
            "heatindex_c": 8.9,
            "heatindex_f": 48.1,
            "dewpoint_c": 5.3,
            "dewpoint_f": 41.6,
            "will_it_rain": 1,
            "chance_of_rain": 85,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 22.7,
            "gust_kph": 36.5,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773619200,
            "time": "2026-03-16 01:00",
            "temp_c": 7.6,
            "temp_f": 45.7,
            "is_day": 0,
            "condition": {
              "text": "Pluie éparse à proximité",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 15.2,
            "wind_kph": 24.5,
            "wind_degree": 267,
            "wind_dir": "W",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0.02,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 80,
            "cloud": 88,
            "feelslike_c": 3.9,
            "feelslike_f": 39,
            "windchill_c": 3.9,
            "windchill_f": 39,
            "heatindex_c": 7.6,
            "heatindex_f": 45.7,
            "dewpoint_c": 4.4,
            "dewpoint_f": 39.8,
            "will_it_rain": 1,
            "chance_of_rain": 87,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 23.6,
            "gust_kph": 38,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773622800,
            "time": "2026-03-16 02:00",
            "temp_c": 6.9,
            "temp_f": 44.3,
            "is_day": 0,
            "condition": {
              "text": "Partiellement nuageux",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 13.4,
            "wind_kph": 21.6,
            "wind_degree": 270,
            "wind_dir": "W",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 83,
            "cloud": 31,
            "feelslike_c": 3.2,
            "feelslike_f": 37.8,
            "windchill_c": 3.2,
            "windchill_f": 37.8,
            "heatindex_c": 6.9,
            "heatindex_f": 44.3,
            "dewpoint_c": 4.3,
            "dewpoint_f": 39.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 20.9,
            "gust_kph": 33.6,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773626400,
            "time": "2026-03-16 03:00",
            "temp_c": 6.2,
            "temp_f": 43.1,
            "is_day": 0,
            "condition": {
              "text": "Clair",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 11.4,
            "wind_kph": 18.4,
            "wind_degree": 266,
            "wind_dir": "W",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 83,
            "cloud": 23,
            "feelslike_c": 2.8,
            "feelslike_f": 37,
            "windchill_c": 2.8,
            "windchill_f": 37,
            "heatindex_c": 6.2,
            "heatindex_f": 43.1,
            "dewpoint_c": 3.6,
            "dewpoint_f": 38.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 18.1,
            "gust_kph": 29.2,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773630000,
            "time": "2026-03-16 04:00",
            "temp_c": 6,
            "temp_f": 42.8,
            "is_day": 0,
            "condition": {
              "text": "Clair",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 13,
            "wind_kph": 20.9,
            "wind_degree": 266,
            "wind_dir": "W",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 81,
            "cloud": 25,
            "feelslike_c": 2.3,
            "feelslike_f": 36.1,
            "windchill_c": 2.3,
            "windchill_f": 36.1,
            "heatindex_c": 6,
            "heatindex_f": 42.8,
            "dewpoint_c": 3,
            "dewpoint_f": 37.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 20.5,
            "gust_kph": 33,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773633600,
            "time": "2026-03-16 05:00",
            "temp_c": 5.9,
            "temp_f": 42.5,
            "is_day": 0,
            "condition": {
              "text": "Partiellement nuageux",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 12.8,
            "wind_kph": 20.5,
            "wind_degree": 265,
            "wind_dir": "W",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 81,
            "cloud": 56,
            "feelslike_c": 2.1,
            "feelslike_f": 35.7,
            "windchill_c": 2.1,
            "windchill_f": 35.7,
            "heatindex_c": 5.9,
            "heatindex_f": 42.5,
            "dewpoint_c": 2.9,
            "dewpoint_f": 37.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 20.2,
            "gust_kph": 32.4,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773637200,
            "time": "2026-03-16 06:00",
            "temp_c": 5.5,
            "temp_f": 41.8,
            "is_day": 0,
            "condition": {
              "text": "Clair",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 13.2,
            "wind_kph": 21.2,
            "wind_degree": 278,
            "wind_dir": "W",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 78,
            "cloud": 16,
            "feelslike_c": 1.5,
            "feelslike_f": 34.7,
            "windchill_c": 1.5,
            "windchill_f": 34.7,
            "heatindex_c": 5.5,
            "heatindex_f": 41.8,
            "dewpoint_c": 1.9,
            "dewpoint_f": 35.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 20.8,
            "gust_kph": 33.4,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773640800,
            "time": "2026-03-16 07:00",
            "temp_c": 5.3,
            "temp_f": 41.6,
            "is_day": 0,
            "condition": {
              "text": "Clair",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 277,
            "wind_dir": "W",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 74,
            "cloud": 12,
            "feelslike_c": 1.4,
            "feelslike_f": 34.6,
            "windchill_c": 1.4,
            "windchill_f": 34.6,
            "heatindex_c": 5.3,
            "heatindex_f": 41.6,
            "dewpoint_c": 1,
            "dewpoint_f": 33.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 19.8,
            "gust_kph": 31.9,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773644400,
            "time": "2026-03-16 08:00",
            "temp_c": 5.6,
            "temp_f": 42,
            "is_day": 1,
            "condition": {
              "text": "Ensoleillé",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 11.2,
            "wind_kph": 18,
            "wind_degree": 269,
            "wind_dir": "W",
            "pressure_mb": 1017,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 75,
            "cloud": 11,
            "feelslike_c": 2,
            "feelslike_f": 35.7,
            "windchill_c": 2,
            "windchill_f": 35.7,
            "heatindex_c": 5.6,
            "heatindex_f": 42,
            "dewpoint_c": 1.6,
            "dewpoint_f": 34.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.2,
            "gust_kph": 27.6,
            "uv": 0.2,
            "short_rad": 37.4,
            "diff_rad": 15.72,
            "dni": 0,
            "gti": 14.21
          },
          {
            "time_epoch": 1773648000,
            "time": "2026-03-16 09:00",
            "temp_c": 7,
            "temp_f": 44.6,
            "is_day": 1,
            "condition": {
              "text": "Ensoleillé",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 11.4,
            "wind_kph": 18.4,
            "wind_degree": 269,
            "wind_dir": "W",
            "pressure_mb": 1017,
            "pressure_in": 30.04,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 70,
            "cloud": 24,
            "feelslike_c": 3.8,
            "feelslike_f": 38.8,
            "windchill_c": 3.8,
            "windchill_f": 38.8,
            "heatindex_c": 7,
            "heatindex_f": 44.6,
            "dewpoint_c": 2,
            "dewpoint_f": 35.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.2,
            "gust_kph": 24.4,
            "uv": 0.6,
            "short_rad": 110,
            "diff_rad": 34.3,
            "dni": 501.56,
            "gti": 0
          },
          {
            "time_epoch": 1773651600,
            "time": "2026-03-16 10:00",
            "temp_c": 8.1,
            "temp_f": 46.6,
            "is_day": 1,
            "condition": {
              "text": "Pluie éparse à proximité",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 14.3,
            "wind_kph": 23,
            "wind_degree": 273,
            "wind_dir": "W",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0.01,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 65,
            "cloud": 61,
            "feelslike_c": 4.7,
            "feelslike_f": 40.4,
            "windchill_c": 4.7,
            "windchill_f": 40.4,
            "heatindex_c": 8.1,
            "heatindex_f": 46.6,
            "dewpoint_c": 1.9,
            "dewpoint_f": 35.5,
            "will_it_rain": 0,
            "chance_of_rain": 69,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 18.1,
            "gust_kph": 29.1,
            "uv": 1.2,
            "short_rad": 179.34,
            "diff_rad": 56.94,
            "dni": 403.84,
            "gti": 1.01
          },
          {
            "time_epoch": 1773655200,
            "time": "2026-03-16 11:00",
            "temp_c": 9.3,
            "temp_f": 48.8,
            "is_day": 1,
            "condition": {
              "text": "Pluie éparse à proximité",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 15.4,
            "wind_kph": 24.8,
            "wind_degree": 279,
            "wind_dir": "W",
            "pressure_mb": 1018,
            "pressure_in": 30.07,
            "precip_mm": 0.02,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 55,
            "cloud": 57,
            "feelslike_c": 6.1,
            "feelslike_f": 42.9,
            "windchill_c": 6.1,
            "windchill_f": 42.9,
            "heatindex_c": 9.3,
            "heatindex_f": 48.8,
            "dewpoint_c": 0.9,
            "dewpoint_f": 33.5,
            "will_it_rain": 1,
            "chance_of_rain": 87,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 18.4,
            "gust_kph": 29.6,
            "uv": 1.8,
            "short_rad": 246.92,
            "diff_rad": 72.61,
            "dni": 402.55,
            "gti": 0.47
          },
          {
            "time_epoch": 1773658800,
            "time": "2026-03-16 12:00",
            "temp_c": 10,
            "temp_f": 50,
            "is_day": 1,
            "condition": {
              "text": "Pluie éparse à proximité",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 14.8,
            "wind_kph": 23.8,
            "wind_degree": 280,
            "wind_dir": "W",
            "pressure_mb": 1019,
            "pressure_in": 30.08,
            "precip_mm": 0.03,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 52,
            "cloud": 99,
            "feelslike_c": 7.1,
            "feelslike_f": 44.7,
            "windchill_c": 7.1,
            "windchill_f": 44.7,
            "heatindex_c": 10,
            "heatindex_f": 50,
            "dewpoint_c": 0.6,
            "dewpoint_f": 33.1,
            "will_it_rain": 1,
            "chance_of_rain": 87,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17,
            "gust_kph": 27.3,
            "uv": 2.2,
            "short_rad": 306.72,
            "diff_rad": 84.63,
            "dni": 417.52,
            "gti": 0
          },
          {
            "time_epoch": 1773662400,
            "time": "2026-03-16 13:00",
            "temp_c": 10.4,
            "temp_f": 50.7,
            "is_day": 1,
            "condition": {
              "text": "Pluie éparse à proximité",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 14.3,
            "wind_kph": 23,
            "wind_degree": 275,
            "wind_dir": "W",
            "pressure_mb": 1019,
            "pressure_in": 30.08,
            "precip_mm": 0.05,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 52,
            "cloud": 100,
            "feelslike_c": 7.6,
            "feelslike_f": 45.7,
            "windchill_c": 7.6,
            "windchill_f": 45.7,
            "heatindex_c": 10.4,
            "heatindex_f": 50.7,
            "dewpoint_c": 0.9,
            "dewpoint_f": 33.6,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.9,
            "gust_kph": 27.2,
            "uv": 2,
            "short_rad": 342.36,
            "diff_rad": 105.01,
            "dni": 400.23,
            "gti": 11.38
          },
          {
            "time_epoch": 1773666000,
            "time": "2026-03-16 14:00",
            "temp_c": 10.4,
            "temp_f": 50.7,
            "is_day": 1,
            "condition": {
              "text": "Pluie éparse à proximité",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 14.3,
            "wind_kph": 23,
            "wind_degree": 267,
            "wind_dir": "W",
            "pressure_mb": 1019,
            "pressure_in": 30.09,
            "precip_mm": 0.07,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 56,
            "cloud": 100,
            "feelslike_c": 7.6,
            "feelslike_f": 45.7,
            "windchill_c": 7.6,
            "windchill_f": 45.7,
            "heatindex_c": 10.4,
            "heatindex_f": 50.7,
            "dewpoint_c": 1.9,
            "dewpoint_f": 35.5,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.8,
            "gust_kph": 28.7,
            "uv": 1.9,
            "short_rad": 290.74,
            "diff_rad": 142.13,
            "dni": 242.73,
            "gti": 72.69
          },
          {
            "time_epoch": 1773669600,
            "time": "2026-03-16 15:00",
            "temp_c": 10.2,
            "temp_f": 50.4,
            "is_day": 1,
            "condition": {
              "text": "Pluie éparse à proximité",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 13.4,
            "wind_kph": 21.6,
            "wind_degree": 258,
            "wind_dir": "W",
            "pressure_mb": 1019,
            "pressure_in": 30.09,
            "precip_mm": 0.09,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 61,
            "cloud": 86,
            "feelslike_c": 7.5,
            "feelslike_f": 45.6,
            "windchill_c": 7.5,
            "windchill_f": 45.6,
            "heatindex_c": 10.3,
            "heatindex_f": 50.5,
            "dewpoint_c": 3.2,
            "dewpoint_f": 37.8,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.2,
            "gust_kph": 27.7,
            "uv": 1.4,
            "short_rad": 252.18,
            "diff_rad": 128.64,
            "dni": 210.02,
            "gti": 69.17
          },
          {
            "time_epoch": 1773673200,
            "time": "2026-03-16 16:00",
            "temp_c": 10.6,
            "temp_f": 51.1,
            "is_day": 1,
            "condition": {
              "text": "Pluie éparse à proximité",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 13.2,
            "wind_kph": 21.2,
            "wind_degree": 257,
            "wind_dir": "WSW",
            "pressure_mb": 1019,
            "pressure_in": 30.08,
            "precip_mm": 0.02,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 61,
            "cloud": 82,
            "feelslike_c": 8.1,
            "feelslike_f": 46.5,
            "windchill_c": 8.1,
            "windchill_f": 46.5,
            "heatindex_c": 10.6,
            "heatindex_f": 51.1,
            "dewpoint_c": 3.5,
            "dewpoint_f": 38.2,
            "will_it_rain": 0,
            "chance_of_rain": 69,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17,
            "gust_kph": 27.4,
            "uv": 0.7,
            "short_rad": 237.96,
            "diff_rad": 122.83,
            "dni": 220.28,
            "gti": 66.23
          },
          {
            "time_epoch": 1773676800,
            "time": "2026-03-16 17:00",
            "temp_c": 10.6,
            "temp_f": 51.1,
            "is_day": 1,
            "condition": {
              "text": "Nuageux",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 13.2,
            "wind_kph": 21.2,
            "wind_degree": 253,
            "wind_dir": "WSW",
            "pressure_mb": 1019,
            "pressure_in": 30.09,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 63,
            "cloud": 74,
            "feelslike_c": 8,
            "feelslike_f": 46.5,
            "windchill_c": 8,
            "windchill_f": 46.5,
            "heatindex_c": 10.6,
            "heatindex_f": 51.1,
            "dewpoint_c": 4,
            "dewpoint_f": 39.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.3,
            "gust_kph": 27.9,
            "uv": 0.3,
            "short_rad": 226.66,
            "diff_rad": 115.95,
            "dni": 263.61,
            "gti": 60.2
          },
          {
            "time_epoch": 1773680400,
            "time": "2026-03-16 18:00",
            "temp_c": 9.7,
            "temp_f": 49.4,
            "is_day": 1,
            "condition": {
              "text": "Nuageux",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 12.3,
            "wind_kph": 19.8,
            "wind_degree": 248,
            "wind_dir": "WSW",
            "pressure_mb": 1019,
            "pressure_in": 30.1,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 69,
            "cloud": 73,
            "feelslike_c": 7,
            "feelslike_f": 44.6,
            "windchill_c": 7,
            "windchill_f": 44.6,
            "heatindex_c": 9.7,
            "heatindex_f": 49.4,
            "dewpoint_c": 4.2,
            "dewpoint_f": 39.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.9,
            "gust_kph": 28.8,
            "uv": 0.1,
            "short_rad": 204.93,
            "diff_rad": 104.29,
            "dni": 350.37,
            "gti": 50.22
          },
          {
            "time_epoch": 1773684000,
            "time": "2026-03-16 19:00",
            "temp_c": 8.8,
            "temp_f": 47.8,
            "is_day": 0,
            "condition": {
              "text": "Couvert",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 11.2,
            "wind_kph": 18,
            "wind_degree": 245,
            "wind_dir": "WSW",
            "pressure_mb": 1020,
            "pressure_in": 30.11,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 73,
            "cloud": 100,
            "feelslike_c": 6.1,
            "feelslike_f": 42.9,
            "windchill_c": 6.1,
            "windchill_f": 42.9,
            "heatindex_c": 8.8,
            "heatindex_f": 47.8,
            "dewpoint_c": 4.3,
            "dewpoint_f": 39.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.5,
            "gust_kph": 28.2,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773687600,
            "time": "2026-03-16 20:00",
            "temp_c": 8.4,
            "temp_f": 47.1,
            "is_day": 0,
            "condition": {
              "text": "Couvert",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 10.5,
            "wind_kph": 16.9,
            "wind_degree": 238,
            "wind_dir": "WSW",
            "pressure_mb": 1020,
            "pressure_in": 30.12,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 78,
            "cloud": 100,
            "feelslike_c": 5.7,
            "feelslike_f": 42.2,
            "windchill_c": 5.7,
            "windchill_f": 42.2,
            "heatindex_c": 8.4,
            "heatindex_f": 47.1,
            "dewpoint_c": 4.7,
            "dewpoint_f": 40.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.5,
            "gust_kph": 26.6,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773691200,
            "time": "2026-03-16 21:00",
            "temp_c": 8.5,
            "temp_f": 47.3,
            "is_day": 0,
            "condition": {
              "text": "Couvert",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 233,
            "wind_dir": "SW",
            "pressure_mb": 1020,
            "pressure_in": 30.12,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 79,
            "cloud": 100,
            "feelslike_c": 5.8,
            "feelslike_f": 42.5,
            "windchill_c": 5.8,
            "windchill_f": 42.5,
            "heatindex_c": 8.5,
            "heatindex_f": 47.3,
            "dewpoint_c": 5,
            "dewpoint_f": 41.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.2,
            "gust_kph": 26.1,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773694800,
            "time": "2026-03-16 22:00",
            "temp_c": 8.7,
            "temp_f": 47.7,
            "is_day": 0,
            "condition": {
              "text": "Couvert",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 11,
            "wind_kph": 17.6,
            "wind_degree": 227,
            "wind_dir": "SW",
            "pressure_mb": 1020,
            "pressure_in": 30.13,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 78,
            "cloud": 100,
            "feelslike_c": 6.1,
            "feelslike_f": 42.9,
            "windchill_c": 6.1,
            "windchill_f": 42.9,
            "heatindex_c": 8.8,
            "heatindex_f": 47.8,
            "dewpoint_c": 5.1,
            "dewpoint_f": 41.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.2,
            "gust_kph": 26,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1773698400,
            "time": "2026-03-16 23:00",
            "temp_c": 8.9,
            "temp_f": 48,
            "is_day": 0,
            "condition": {
              "text": "Couvert",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 11.4,
            "wind_kph": 18.4,
            "wind_degree": 227,
            "wind_dir": "SW",
            "pressure_mb": 1020,
            "pressure_in": 30.13,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 77,
            "cloud": 100,
            "feelslike_c": 6.1,
            "feelslike_f": 43,
            "windchill_c": 6.1,
            "windchill_f": 43,
            "heatindex_c": 8.9,
            "heatindex_f": 47.9,
            "dewpoint_c": 5,
            "dewpoint_f": 41,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17,
            "gust_kph": 27.4,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          }
        ]
      }
    ]
  }
}

export default response;